### ISSUE TITLE
Can't call CreativeService.updateCreatives --> Unexpected wrapper element updateCreatives found.

### ISSUE THREAD

**Issue by gerardcsaperas** [thewizarodofoz/google-ad-manager-api#18]
Hi there!

First of all, thank you for the package, it's really helpful.

I just found an unexpected error when trying to update a Creative using `CreativeService.updateCreatives`

I'm just trying to:
1) Get a Creative by statement (OK)
2) Update a field (NOK, Throws Error)

This is my controller function:
```
async function operationsValidation(req, res) {
  try {
    // 1. Get CreativeService
    const CreativeService = await dfp.getService(
      "CreativeService",
      req.body.authToken
    );

    // 2. Get Creatives by statement (by Creative ID)
    const creativeRequest = await CreativeService.getCreativesByStatement({
      filterStatement: {
        query: `WHERE creativeId = ${req.body.creativeId}`,
      },
    });

    const creative = creativeRequest.results[0];

    if (!creative) {
      res.status(500).json();
    }

    // 3. Update a random field
    creative.name = "Angla Test";

    // 4. Send update request --> This throws an error
    const updateCreative = await CreativeService.updateCreatives([creative]);

    res.send(updateCreative);
  } catch (e) {
    console.log(e);
    res.status(500).send(e);
  }
}
```

This is the error thrown:
```
Error: soap:Client: Unexpected wrapper element updateCreatives found.   Expected {https://www.google.com/apis/ads/publisher/v202105}updateCreatives.
    at finish (/Users/ignasidedieuburrel/Documents/Konodrac/Repos/gam-validator-api/node_modules/soap/lib/wsdl/index.js:457:33)
    at WSDL.xmlToObject (/Users/ignasidedieuburrel/Documents/Konodrac/Repos/gam-validator-api/node_modules/soap/lib/wsdl/index.js:438:16)
    at parseSync (/Users/ignasidedieuburrel/Documents/Konodrac/Repos/gam-validator-api/node_modules/soap/lib/client.js:274:36)
    at /Users/ignasidedieuburrel/Documents/Konodrac/Repos/gam-validator-api/node_modules/soap/lib/client.js:443:24
    at Request._callback (/Users/ignasidedieuburrel/Documents/Konodrac/Repos/gam-validator-api/node_modules/soap/lib/http.js:162:17)
    at Request.self.callback (/Users/ignasidedieuburrel/Documents/Konodrac/Repos/gam-validator-api/node_modules/request/request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.<anonymous> (/Users/ignasidedieuburrel/Documents/Konodrac/Repos/gam-validator-api/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:394:28)
    at IncomingMessage.<anonymous> (/Users/ignasidedieuburrel/Documents/Konodrac/Repos/gam-validator-api/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Sorry if it's obvious, but I can't seem to find the reason.

Thank you so much in advance,

Gerard

**Comment by gerardcsaperas** [comment]
We solved it. I know nothing about SOAP, but I write the answer just in case it may be useful to someone.

The error was due to the SOAP request being sent to Google Ad Manager API not containing `xmlns="https://www.google.com/apis/ads/publisher/v202105"` in the `<updateCreatives>` opening tag.

**This is correct**
`<updateCreatives xmlns="https://www.google.com/apis/ads/publisher/v202105">...</updateCreatives>`
**This is incorrect**
`<updateCreatives>...</updateCreatives>`

That was being caused due to passing an array as the argument to
```
const updateCreative = await CreativeService.updateCreatives([creative]);
```

When you perform a `CreativeService.updateCreatives`, you don't have to pass an array of `Creatives` to be updated (as the [Google Ad Manager API docs](https://developers.google.com/ad-manager/api/reference/v202105/CreativeService#updatecreatives) suggest).

Instead, the object to be passed should be:
```
let updatedCreative = {
    creatives: updatedCreative // Your updated creative Object
}
```

Our function finally ended up like this.

```
async function operationsValidation(req, res) {
  try {
    // 1. Get CreativeService
    const CreativeService = await dfp.getService(
      "CreativeService",
      req.body.authToken
    );

    // 2. Get Creatives by statement (by Creative ID)
    const creativeRequest = await CreativeService.getCreativesByStatement({
      filterStatement: {
        query: `WHERE creativeId = ${req.body.creativeId}`,
      },
    });

    const creative = creativeRequest.results[0];

    if (!creative) {
      res.status(500).json();
    }

    // 3. Update a random field
    creative.name = "Updated Name";

    /*
    * Put the creative to be updated inside
    * its own JSON with the key `creatives`
    * in it.
    *
    * This will create the XML <creatives /> tag
    * in the SOAP request.
    */
    let updatedCreative = {
          creatives: creative
    }

    // 4. Send update request ---> WORKS!
    const updateCreative = await CreativeService.updateCreatives(updatedCreative);

    res.send(updateCreative);
  } catch (e) {
    console.log(e);
    res.status(500).send(e);
  }
}
```
